apps/blog/urls.py
"""Blog app of Smyt blog site URL Configuration."""

from django.urls import path

import apps.blog.views as v

app_name = 'blog'

urlpatterns = [
    path('author/<int:author_id>/<slug:author_slug>/', v.BlogListView.as_view(), name="author"),
    path('author/<int:author_id>/', v.BlogListView.as_view(), name="author"),
    path('tag/<slug:tag_slug>/', v.BlogListView.as_view(), name="tag"),
    path('<slug:slug>/', v.BlogPostView.as_view(), name="post"),
    path('', v.BlogListView.as_view(), name='index'),
]

smyt_blog/urls.py
"""Smyt blog site URL Configuration."""

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

import apps.blog.urls

urlpatterns = [
    path('{}admin/'.format(settings.BASE_NAME), admin.site.urls),
    re_path(r'^{}ckeditor/'.format(settings.BASE_NAME), include('ckeditor_uploader.urls')),
    path('{}'.format(settings.BASE_NAME), include(apps.blog.urls, namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
"""Blog application models."""

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.safestring import mark_safe
from django.utils.text import gettext_lazy as _


class Author(models.Model):
    """Blog post Author."""

    user = models.OneToOneField(
        User,
        verbose_name=_('Linked user'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    name = models.TextField(_('Name'))
    slug = models.SlugField(_('Url name'), default="")
    appointment = models.TextField(_('Position at work'))
    avatar = models.ImageField(_('Avatar'), upload_to="author")

    def avatar_tag(self):
        """Change output avatar field."""
        return mark_safe('<img src="{}" style="max-width: 108px;" />'.format(self.avatar.url))

    avatar_tag.short_description = _('Image')

    def __str__(self):
        """View for Author object."""
        return "{name}, {appointment}".format(
            name=self.name,
            appointment=self.appointment
        )

    class Meta:
        """Meta Class for Author class."""

        verbose_name = _('Author')
        verbose_name_plural = _('Authors')
        ordering = ['name']


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create Author if user created."""
    if created:
        Author.objects.create(
            user=instance,
            name=instance.username
        )


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """Save Author linked with user."""
    instance.author.save()


class Tag(models.Model):
    """Blog tag."""

    title = models.TextField(_('Name'))
    slug = models.SlugField(_('Url name'), unique=True)

    def __str__(self):
        """View for Tag object."""
        return self.title

    class Meta:
        """Meta Class for Tag class."""

        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')
        ordering = ['title']


class BlogPost(models.Model):
    """Blog post model."""

    title = models.TextField(_('Title'))
    url = models.SlugField(_('Url'), unique=True)
    short_description = models.TextField(_('Short description'))
    text = models.TextField(_('Text'))
    image = models.ImageField(_('Image'), upload_to="articles", null=True, blank=True)
    tags = models.ManyToManyField("Tag", related_name="blog_posts", blank=True)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    views_count = models.IntegerField(_('Views count'), default=0)
    real_views_count = models.IntegerField(_('Real views count'), default=0)
    published_at = models.DateTimeField(_('Date published'), null=True, blank=True)
    is_published = models.BooleanField(_('Is publish?'))

    def __str__(self):
        """View for BlogPost object."""
        return "{title}, id: {pk}".format(
            title=self.title,
            pk=self.pk,
        )

    class Meta:
        """Meta Class for BlogPost class."""

        verbose_name = _('Article')
        verbose_name_plural = _('Articles')

apps/blog/views.py
"""Blog app views for smyt blog site."""

from datetime import datetime
from django.db.models import F
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView

from apps.blog.models import BlogPost


class BlogListView(TemplateView):
    """View with published blog posts."""

    template_name = "index.html"
    DATE_FORMAT = '%Y.%d.%m %H:%M:%S'

    def get_context_data(self, **kwargs):
        """Add additional data to context page."""
        data = super().get_context_data(**kwargs)
        posts = BlogPost.objects.all()\
            .select_related("author")\
            .prefetch_related("tags")\
            .filter(is_published=True)\
            .order_by('-published_at', 'id')

        if 'lastPublished' in self.request.GET:
            last_published = datetime.strptime(self.request.GET['lastPublished'], self.DATE_FORMAT)
            posts = posts.filter(published_at__lt=last_published)

        if 'tag_slug' in kwargs:
            posts = posts.filter(tags__slug__in=(kwargs['tag_slug'], ))

        if 'author_id' in kwargs:
            posts = posts.filter(author=kwargs['author_id'])

        data['has_more'] = posts.count() > 10

        posts = list(posts[:10])
        data['last_published'] = min([i.published_at for i in posts]) if posts else None
        data['last_published'] = data['last_published'].strftime(self.DATE_FORMAT) if data['last_published'] else None
        data['posts'] = posts

        return data

    def get(self, request, *args, **kwargs):
        """Process get request, added additional processing for ajax requests."""
        if self.request.is_ajax():
            data = self.get_context_data(**kwargs)
            return JsonResponse({
                'has_more': data['has_more'],
                'lastPublished': data['last_published'],
                'content': render_to_string("partials/posts_list.html", data, request=self.request)
            })

        return super().get(request, *args, **kwargs)


class BlogPostView(TemplateView):
    """View for displaying a blog post."""

    template_name = "post.html"

    def get_context_data(self, **kwargs):
        """Add additional data to context page."""
        data = super().get_context_data(**kwargs)
        post = get_object_or_404(BlogPost, url=kwargs['slug'])

        if not self.request.user.is_authenticated:
            BlogPost.objects.filter(pk=post.pk).update(
                views_count=F('views_count') + 1,
                real_views_count=F('real_views_count') + 1
            )

        data['post'] = post
        return data

templates/_base.html
{% load static i18n %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name='yandex-verification' content='7315ec443cd7677a' />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="{% static "img/favicon.ico" %}" >
    <link rel="icon" type="image/png" href="{% static "img/favicon.ico" %}">
    <title>{% block title %}{% trans 'Blog' %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
{#    <base href="{{ settings.BASE_NAME }}">#}

    <!-- Main js file -->
    <script src="{% static "js/jquery-min.js" %}" defer></script>
    <script src="{% static "js/highlight.pack.js" %}"></script>
    <script src="{% static "js/main.js" %}" defer></script>

    <!-- Page specific js files -->
    <link rel="stylesheet" href="{% static "build/main.css" %}">
    {% block head %}
    {% endblock %}
	<!-- Yandex.Metrika counter -->
	<script type="text/javascript" >
		(function (d, w, c) {
			(w[c] = w[c] || []).push(function() {
				try {
					w.yaCounter7872433 = new Ya.Metrika2({
						id:7872433,
						clickmap:true,
						trackLinks:true,
						accurateTrackBounce:true,
						webvisor:true
					});
				} catch(e) { }
			});

			var n = d.getElementsByTagName("script")[0],
				s = d.createElement("script"),
				f = function () { n.parentNode.insertBefore(s, n); };
			s.type = "text/javascript";
			s.async = true;
			s.src = "https://mc.yandex.ru/metrika/tag.js";

			if (w.opera == "[object Opera]") {
				d.addEventListener("DOMContentLoaded", f, false);
			} else { f(); }
		})(document, window, "yandex_metrika_callbacks2");
	</script>
	<noscript><div><img src="https://mc.yandex.ru/watch/7872433"
	style="position:absolute; left:-9999px;" alt="" /></div></noscript>
	<!-- /Yandex.Metrika counter -->
</head>
<body>
<header>
    <div class="container">
        <div class="header-top">
            <ul>
                <li>WWW.SMYT.RU</li>
                <li><a href="http://smytsoft.com/">ENGLISH VERSION</a></li>
            </ul>
        </div>
        <div class="header-logo">
            <img src="{% static "img/logo.png" %}">
        </div>
        <div class="header-menu">
            <div class="header-btn">
                <a href="#"><i class="fa fa-bars" aria-hidden="true"></i></a>
            </div>
            <ul>
                <li class="m1"><a href="http://smyt.ru/">{% trans 'Main page' %}</a></li>
                <li class="m2"><a href="http://smyt.ru/projects/">{% trans 'Projects' %}</a></li>
                <li class="m3"><a href="http://smyt.ru/services/">{% trans 'Services' %}</a></li>
                <li class="m4"><a href="http://smyt.ru/support/">{% trans 'Support' %}</a></li>
                <li class="m5"><a href="http://smyt.ru/company/">{% trans 'Company' %}</a></li>
                <li class="m6"><a href="http://smyt.ru/contacts/">{% trans 'Contacts' %}</a></li>
            </ul>
        </div>
    </div>
</header>

{% block content %}

{% endblock %}
<footer>
    <div class="footer-content">
        <ul>
            <li><span>{% trans 'Call us' %}: </span>{% trans 'in Saint Petersburg' %} +7 (812) 309-72-84</li>
            <li>{% trans 'Develop by SMYT company' %}</li>
        </ul>
    </div>
</footer>

{% block scripts %}
    <script>
        hljs.initHighlightingOnLoad();
    </script>
{% endblock %}
</body>
</html>

templates/index.html
{% extends "_base.html" %}
{% load static i18n %}

{% block content %}
    <section class="blog">
        <div class="container">
            <div class="posts">
                {% include "partials/posts_list.html" %}
            </div>
            {% if has_more %}
                <div class="blog-btn" data-last-published="{{ last_published }}">
                    <a href="#">{% trans 'View previous results' %}</a>
                </div>
            {% endif %}
        </div>
    </section>
{% endblock %}

templates/partials/posts_item.html
<div class="blog-content">
    <div class="blog-content-personal">
        <div class="blog-personal-date">
            <h4>{{ post.published_at|date:"d b Y" }}</h4>
        </div>
        <div class="blog-personal-img">
            {% if post.author.avatar %}
                <img src="{{ post.author.avatar.url }}">
            {% endif %}
        </div>
        <div class="blog-personal-name">
            <p>{{ post.author.name }}
            <div class="blog-personal-appointment">
                <span>{{ post.author.appointment }}</span>
            </div>
        </div>
    </div>
    <div class="blog-content-about">
        {% if post.image %}
            <a href="{% url 'blog:post' slug=post.url %}" class="blog-about-img">
                <img src="{{ post.image.url }}">
            </a>
        {% endif %}
        <div class="blog-about-title">
            <h2><a href="{% url 'blog:post' slug=post.url %}">{{ post.title }}</a></h2>
        </div>
        <div class="blog-about-text">
            {{ post.short_description|safe }}
        </div>
        <div class="blog-about-views">
            <ul>
                <li>
                    <i class="fa fa-tag" aria-hidden="true"></i>
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:tag" tag_slug=tag.slug %}">{{ tag.title }}{% if not forloop.last %}, {% endif %}</a>
                    {% endfor %}
                </li>
                <li>
                    <i class="fa fa-eye" aria-hidden="true"></i>
                    <p>{{ post.views_count }}</p>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/partials/posts_list.html
{% for post in posts %}
    {% include "partials/posts_item.html" with post=post %}
{% endfor %}

templates/post.html
{% extends "_base.html" %}
{% load static i18n %}

{% block title %}{{ post.title }}{% endblock %}
{% block head %}
    <meta property="og:url"           content="{{ request.build_absolute_uri }}" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="{{ post.title }}" />
    <meta property="og:description"   content="{{ post.short_description|striptags }}" />
    {% if post.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ post.image.url }}"/>
    {% endif %}
{% endblock %}

{% block content %}
    <section class="post">
        <div class="container">
            <div class="post-title">
                <h1>{{ post.title }}</h1>
                <ul>
                    <li>
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <p>{{ post.author.name }}, {{ post.author.appointment }}
                        <p>
                    </li>
                    <li>
                        <i class="fa fa-calendar-o" aria-hidden="true"></i>
                        <span>{{ post.published_at|date:"d b Y" }}</span>
                    </li>
                </ul>
            </div>
            <div class="post-content">
                <div class="post-content-about">
                    {{ post.text|safe }}
                </div>
            </div>
            <div class="post-btns">
                <ul>
                    <li class="facebook">
                        <a href="#" onclick="share_fb('{{ request.build_absolute_uri }}');return false;" rel="nofollow" target="_blank">
                            <i class="fab fa-facebook-f" aria-hidden="true"></i>
                            Facebook
                        </a>
                    </li>
                    <li class="twitter">
                        <a href="#" onclick="share_twitter('{{ request.build_absolute_uri }}');return false;" rel="nofollow" target="_blank">
                            <i class="fab fa-twitter" aria-hidden="true"></i>
                            Twitter
                        </a>
                    </li>
                    <li class="vk">
                        <a href="#" onclick="share_vk('{{ request.build_absolute_uri }}');return false;" rel="nofollow" target="_blank">
                            <i class="fab fa-vk" aria-hidden="true"></i>
                            VK
                        </a>
                    </li>
                </ul>
            </div>

            <div id="fb-root"></div>
            <script>
                function share_fb(url) {
                    url = 'https://www.facebook.com/sharer/sharer.php?u='+url;
                    {% if post.image %}
                        url += "&picture={{ request.scheme }}://{{ request.get_host }}{{ post.image.url }}";
                    {% endif %}
                    window.open(url,'facebook-share-dialog',"width=626, height=436")
                }

                function share_twitter(url) {
                    window.open('http://twitter.com/share?url=' + url, 'twitter-share-dialog', "width=626, height=436")
                }

                function share_vk(url) {
                    window.open('https://vk.com/share.php?title={{ post.title }}&noparse=false&url=' + url, 'vk-share-dialog', "width=626, height=436")
                }
            </script>
            <div class="post-link">
                <a href="{% url 'blog:index' %}">{% trans 'View all posts' %}</a>
            </div>
        </div>
    </section>
{% endblock %}